---
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '**.json'
  pull_request:
    paths:
      - '**.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://nanozoo/jq:1.6--0bafc15
      - name: Check if a json is sorted
        run: |
          for json in assets/json/*.json ; do
            diff <(jq -S . $json) $json || exit 1
          done
